### ISSUE TITLE
Compile Error on Linux Mint XFCE 16.04

### ISSUE THREAD

**Issue by kanehekili** [bernhardu/dvbcut-deb#1]
Hi,
as as longterm user of DVBCut I appreciate very much your efforts to "uplift" the software. Despite loading all the given dev libs i get the follwing error:
```
g++ -g -O2 -Wall -Wcast-align -DPACKAGE_NAME=\"\" -DPACKAGE_TARNAME=\"\" -DPACKAGE_VERSION=\"\" -DPACKAGE_STRING=\"\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DHAVE_LIB_SWSCALE=1 -DHAVE_LIB_MAD=1 -DHAVE_LIB_A52=1 -DHAVE_LIB_AO=1 -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_AO_AO_H=1 -DHAVE_MAD_H=1 -DHAVE_STDINT_H=1 -DHAVE_A52DEC_A52_H=1 -DHAVE_STDLIB_H=1 -DHAVE_UNISTD_H=1 -DHAVE_SYS_PARAM_H=1 -DHAVE_GETPAGESIZE=1 -DHAVE_MMAP=1 -D__STDC_LIMIT_MACROS=1 -D__STDC_CONSTANT_MACROS=1 -D_FILE_OFFSET_BITS=64 -I/usr/include -I/usr/include/ffmpeg -I/include -fPIC -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/x86_64-linux-gnu/qt5 -I. -I/usr/include -I/usr/include/ffmpeg -I/include -fPIC -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/x86_64-linux-gnu/qt5 -I.  -c -o buffer.o buffer.cpp
g++ -g -O2 -Wall -Wcast-align -DPACKAGE_NAME=\"\" -DPACKAGE_TARNAME=\"\" -DPACKAGE_VERSION=\"\" -DPACKAGE_STRING=\"\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DHAVE_LIB_SWSCALE=1 -DHAVE_LIB_MAD=1 -DHAVE_LIB_A52=1 -DHAVE_LIB_AO=1 -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_AO_AO_H=1 -DHAVE_MAD_H=1 -DHAVE_STDINT_H=1 -DHAVE_A52DEC_A52_H=1 -DHAVE_STDLIB_H=1 -DHAVE_UNISTD_H=1 -DHAVE_SYS_PARAM_H=1 -DHAVE_GETPAGESIZE=1 -DHAVE_MMAP=1 -D__STDC_LIMIT_MACROS=1 -D__STDC_CONSTANT_MACROS=1 -D_FILE_OFFSET_BITS=64 -I/usr/include -I/usr/include/ffmpeg -I/include -fPIC -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/x86_64-linux-gnu/qt5 -I. -I/usr/include -I/usr/include/ffmpeg -I/include -fPIC -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/x86_64-linux-gnu/qt5 -I.  -c -o dvbcut.o dvbcut.cpp
In file included from dvbcut.h:36:0,
                 from dvbcut.cpp:59:
ui_dvbcutbase.h:13:25: fatal error: QtGui/QAction: No such file or directory
compilation terminated.
```
Could you give a hint ,what is missing?
Regards Kanehekili

**Comment by bernhardu** [comment]
Hello Kanehekili,
as the error comes from the generated ui_*.h I think it was produced by Qt4 uic.

You have probably also the Qt4 development packages installed?

If yes try to remove ui__.h and moc__.cpp and

export QT_SELECT=qt5
make

Kind regards,
Bernhard

Am 18. November 2016 23:51:22 MEZ, schrieb Kanehekili notifications@github.com:

> Hi,
> as as longterm user of DVBCut I appreciate very much your efforts to
> "uplift" the software. Despite loading all the given dev libs i get the
> follwing error:
> 
> ```
> g++ -g -O2 -Wall -Wcast-align -DPACKAGE_NAME=\"\"
> -DPACKAGE_TARNAME=\"\" -DPACKAGE_VERSION=\"\" -DPACKAGE_STRING=\"\"
> -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DHAVE_LIB_SWSCALE=1
> -DHAVE_LIB_MAD=1 -DHAVE_LIB_A52=1 -DHAVE_LIB_AO=1 -DSTDC_HEADERS=1
> -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1
> -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1
> -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1
> -DHAVE_AO_AO_H=1 -DHAVE_MAD_H=1 -DHAVE_STDINT_H=1 -DHAVE_A52DEC_A52_H=1
> -DHAVE_STDLIB_H=1 -DHAVE_UNISTD_H=1 -DHAVE_SYS_PARAM_H=1
> -DHAVE_GETPAGESIZE=1 -DHAVE_MMAP=1 -D__STDC_LIMIT_MACROS=1
> -D__STDC_CONSTANT_MACROS=1 -D_FILE_OFFSET_BITS=64 -I/usr/include
> -I/usr/include/ffmpeg -I/include -fPIC
> -I/usr/include/x86_64-linux-gnu/qt5/QtXml
> -I/usr/include/x86_64-linux-gnu/qt5
> -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets
> -I/usr/include/x86_64-linux-gnu/qt5
> -I/usr/include/x86_64-linux-gnu/qt5/QtGui
> -I/usr/include/x86_64-linux-gnu/qt5
> -I/usr/include/x86_64-linux-gnu/qt5/QtCore
> -I/usr/include/x86_64-linux-gnu/qt5 -I. -I/usr/include
> -I/usr/include/ffmpeg -I/include -fPIC
> -I/usr/include/x86_64-linux-gnu/qt5/QtXml
> -I/usr/include/x86_64-linux-gnu/qt5
> -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets
> -I/usr/include/x86_64-linux-gnu/qt5
> -I/usr/include/x86_64-linux-gnu/qt5/QtGui
> -I/usr/include/x86_64-linux-gnu/qt5
> -I/usr/include/x86_64-linux-gnu/qt5/QtCore
> -I/usr/include/x86_64-linux-gnu/qt5 -I.  -c -o buffer.o buffer.cpp
> g++ -g -O2 -Wall -Wcast-align -DPACKAGE_NAME=\"\"
> -DPACKAGE_TARNAME=\"\" -DPACKAGE_VERSION=\"\" -DPACKAGE_STRING=\"\"
> -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DHAVE_LIB_SWSCALE=1
> -DHAVE_LIB_MAD=1 -DHAVE_LIB_A52=1 -DHAVE_LIB_AO=1 -DSTDC_HEADERS=1
> -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1
> -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1
> -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1
> -DHAVE_AO_AO_H=1 -DHAVE_MAD_H=1 -DHAVE_STDINT_H=1 -DHAVE_A52DEC_A52_H=1
> -DHAVE_STDLIB_H=1 -DHAVE_UNISTD_H=1 -DHAVE_SYS_PARAM_H=1
> -DHAVE_GETPAGESIZE=1 -DHAVE_MMAP=1 -D__STDC_LIMIT_MACROS=1
> -D__STDC_CONSTANT_MACROS=1 -D_FILE_OFFSET_BITS=64 -I/usr/include
> -I/usr/include/ffmpeg -I/include -fPIC
> -I/usr/include/x86_64-linux-gnu/qt5/QtXml
> -I/usr/include/x86_64-linux-gnu/qt5
> -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets
> -I/usr/include/x86_64-linux-gnu/qt5
> -I/usr/include/x86_64-linux-gnu/qt5/QtGui
> -I/usr/include/x86_64-linux-gnu/qt5
> -I/usr/include/x86_64-linux-gnu/qt5/QtCore
> -I/usr/include/x86_64-linux-gnu/qt5 -I. -I/usr/include
> -I/usr/include/ffmpeg -I/include -fPIC
> -I/usr/include/x86_64-linux-gnu/qt5/QtXml
> -I/usr/include/x86_64-linux-gnu/qt5
> -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets
> -I/usr/include/x86_64-linux-gnu/qt5
> -I/usr/include/x86_64-linux-gnu/qt5/QtGui
> -I/usr/include/x86_64-linux-gnu/qt5
> -I/usr/include/x86_64-linux-gnu/qt5/QtCore
> -I/usr/include/x86_64-linux-gnu/qt5 -I.  -c -o dvbcut.o dvbcut.cpp
> In file included from dvbcut.h:36:0,
>                 from dvbcut.cpp:59:
> ui_dvbcutbase.h:13:25: fatal error: QtGui/QAction: No such file or
> directory
> compilation terminated.
> ```
> 
> Could you give a hint ,what is missing?
> Regards Kanehekili
> 
> ## 
> 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/bernhardu/dvbcut-deb/issues/1

## 

Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by kanehekili** [comment]
Hi Bernard, 
thanks for the fast reply. I removed the following packages :
sudo apt-get purge libqt4-dev-bin libqt4-qt3support

executed export QT_SELECT=q5 
make:
In file included from mpgfile.h:34:0,
                 from dvbcut.h:35,
                 from dvbcut.cpp:59:
stream.h: In member function ‘void stream::setvideoencodingparameters(bool)’:
stream.h:73:11: warning: ‘AVCodecContext::rc_buffer_aggressivity’ is deprecated [-Wdeprecated-declarations]
     avcc->rc_buffer_aggressivity=1.0;
           ^
In file included from stream.h:27:0,
                 from mpgfile.h:34,
                 from dvbcut.h:35,
                 from dvbcut.cpp:59:
/usr/include/x86_64-linux-gnu/libavcodec/avcodec.h:2618:11: note: declared here
     float rc_buffer_aggressivity;
           ^
In file included from mpgfile.h:34:0,
                 from dvbcut.h:35,
                 from dvbcut.cpp:59:
stream.h:73:11: warning: ‘AVCodecContext::rc_buffer_aggressivity’ is deprecated [-Wdeprecated-declarations]
     avcc->rc_buffer_aggressivity=1.0;
           ^
In file included from stream.h:27:0,
                 from mpgfile.h:34,
                 from dvbcut.h:35,
                 from dvbcut.cpp:59:
/usr/include/x86_64-linux-gnu/libavcodec/avcodec.h:2618:11: note: declared here
     float rc_buffer_aggressivity;
           ^
In file included from mpgfile.h:34:0,
                 from dvbcut.h:35,
                 from dvbcut.cpp:59:
stream.h:73:11: warning: ‘AVCodecContext::rc_buffer_aggressivity’ is deprecated [-Wdeprecated-declarations]
     avcc->rc_buffer_aggressivity=1.0;
           ^
In file included from stream.h:27:0,
                 from mpgfile.h:34,
                 from dvbcut.h:35,
                 from dvbcut.cpp:59:
/usr/include/x86_64-linux-gnu/libavcodec/avcodec.h:2618:11: note: declared here
     float rc_buffer_aggressivity;
           ^
In file included from mpgfile.h:34:0,
                 from dvbcut.h:35,
                 from dvbcut.cpp:59:
stream.h:74:11: warning: ‘AVCodecContext::lmax’ is deprecated [-Wdeprecated-declarations]
     avcc->lmax= FF_QP2LAMBDA * 2;
           ^
In file included from stream.h:27:0,
                 from mpgfile.h:34,
                 from dvbcut.h:35,
                 from dvbcut.cpp:59:
/usr/include/x86_64-linux-gnu/libavcodec/avcodec.h:2677:9: note: declared here
     int lmax;
         ^
In file included from mpgfile.h:34:0,
                 from dvbcut.h:35,
                 from dvbcut.cpp:59:
stream.h:74:11: warning: ‘AVCodecContext::lmax’ is deprecated [-Wdeprecated-declarations]
     avcc->lmax= FF_QP2LAMBDA * 2;
           ^
In file included from stream.h:27:0,
                 from mpgfile.h:34,
                 from dvbcut.h:35,
                 from dvbcut.cpp:59:
/usr/include/x86_64-linux-gnu/libavcodec/avcodec.h:2677:9: note: declared here
     int lmax;
         ^
In file included from mpgfile.h:34:0,
                 from dvbcut.h:35,
                 from dvbcut.cpp:59:
stream.h:74:11: warning: ‘AVCodecContext::lmax’ is deprecated [-Wdeprecated-declarations]
     avcc->lmax= FF_QP2LAMBDA * 2;
           ^
In file included from stream.h:27:0,
                 from mpgfile.h:34,
                 from dvbcut.h:35,
                 from dvbcut.cpp:59:
/usr/include/x86_64-linux-gnu/libavcodec/avcodec.h:2677:9: note: declared here
     int lmax;
         ^
dvbcut.cpp: In member function ‘virtual void dvbcut::fileExport()’:
dvbcut.cpp:583:3: error: ‘unique_ptr’ is not a member of ‘std’
   std::unique_ptr<exportdialog> expd(new exportdialog(QString::fromStdString(ex
   ^
dvbcut.cpp:583:31: error: expected primary-expression before ‘>’ token
   std::unique_ptr<exportdialog> expd(new exportdialog(QString::fromStdString(ex
                               ^
dvbcut.cpp:583:93: error: ‘expd’ was not declared in this scope
 tr<exportdialog> expd(new exportdialog(QString::fromStdString(expfilen),this));
                                                                              ^
dvbcut.cpp:728:3: error: ‘unique_ptr’ is not a member of ‘std’
   std::unique_ptr<muxer> mux;
   ^
dvbcut.cpp:728:24: error: expected primary-expression before ‘>’ token
   std::unique_ptr<muxer> mux;
                        ^
dvbcut.cpp:728:26: error: ‘mux’ was not declared in this scope
   std::unique_ptr<muxer> mux;
                          ^
dvbcut.cpp:740:13: error: ‘unique_ptr’ is not a member of ‘std’
       mux = std::unique_ptr<muxer>(new mpegmuxer(audiostreammask,*mpg,out_file.
             ^
dvbcut.cpp:740:34: error: expected primary-expression before ‘>’ token
       mux = std::unique_ptr<muxer>(new mpegmuxer(audiostreammask,*mpg,out_file.
                                  ^
dvbcut.cpp:743:13: error: ‘unique_ptr’ is not a member of ‘std’
       mux = std::unique_ptr<muxer>(new lavfmuxer("dvd",audiostreammask,*mpg,out
             ^
dvbcut.cpp:743:34: error: expected primary-expression before ‘>’ token
       mux = std::unique_ptr<muxer>(new lavfmuxer("dvd",audiostreammask,*mpg,out
                                  ^
dvbcut.cpp:746:13: error: ‘unique_ptr’ is not a member of ‘std’
       mux = std::unique_ptr<muxer>(new lavfmuxer("mpegts",audiostreammask,*mpg,
             ^
dvbcut.cpp:746:34: error: expected primary-expression before ‘>’ token
       mux = std::unique_ptr<muxer>(new lavfmuxer("mpegts",audiostreammask,*mpg,
                                  ^
dvbcut.cpp:750:13: error: ‘unique_ptr’ is not a member of ‘std’
       mux = std::unique_ptr<muxer>(new mpegmuxer(audiostreammask,*mpg,out_file.
             ^
dvbcut.cpp:750:34: error: expected primary-expression before ‘>’ token
       mux = std::unique_ptr<muxer>(new mpegmuxer(audiostreammask,*mpg,out_file.
                                  ^
<builtin>: recipe for target 'dvbcut.o' failed
make[1]: *** [dvbcut.o] Error 1
make[1]: Leaving directory '/home/matze/Downloads/dvbcut-deb-master/src'
Makefile:42: recipe for target 'all' failed
make: *** [all] Error 2

As gcc compiler there are 
gcc            4:5.3.1-1ubu amd64 
gcc-5          5.4.0-6ubunt amd64
gcc-6-base:amd 6.0.1-0ubunt amd64

Sorry, but I,m not a C-guy, but a great fan of DVB-cut. I've created a (inferior) clone for mp4 with python (https://github.com/kanehekili/VideoCut), so my hope is to learn more about this project. 

Regards Mathias

**Comment by bernhardu** [comment]
In this case I was probably too fast for adopting std::unique_ptr that I integrated because of the gcc-6 warning.
But right now you could simply revert this commit like shown below.
```
git clone https://github.com/bernhardu/dvbcut-deb.git
cd dvbcut-deb
git revert --no-edit 0b630ad2373dd5dd0b3c996608377de2b93cc35d
export QT_SELECT=qt5
autoconf
./configure --with-ffmpeg=/usr
make -j2

src/dvbcut
```

**Comment by kanehekili** [comment]
Thank you!

It worked and it looks great.

Regards Mathias
