### ISSUE TITLE
Several issues discovered in Version 0.7.4

### ISSUE THREAD

**Issue by cypline** [bernhardu/dvbcut-deb#15]
Hi,

first of all thanks for the continuation of dvbcut. I really love this program. Unfortunately when I now tried to get the newest version running on my system I discovered several issues as follows. I will provide fixes for them and will ask to get them merged.

1. The diff display was not working any longer after patch  6249173d1e4403c3e2c4b7b872e43349a512bfcf. The patch itself does work, but not any more for the differenceimageprovider to display the difference between two pictures, as the layout of the picture does not fit any longer to the handling of it. It must be a 32 bit layout in memory, else it would not work, but after the patch there is only a 24 bit based picture in the memory and the check for 32 bit fails (line 91) and skips the further processing, which would fail anyhow, because of the incorrect layout.

2. With Patch 1dec08090fa824398e8397dc4e99fefd7eb5a84a and the removal of "register_all" renders the program unusable if compiled against ffmpeg less the major version 58 - ffmpeg version 4.x because it produces codec not found errors and nothing is loaded.

3. With ffmpeg version library version 57.14 codecparm was introduced which leeds to undesired behaviour up to core dumps when trying to save a file via lavfmuxer.

4. Indipendent, I encountered problems with streams broadcasted in Germany from the RTL group, all of them (RTL, RTL2, VOX, Nitro, superRTL). Also using the lavfmuxer resulted in core dumps, because the sample_rate could not be set as the header of the first packets of the mp2 stream are invalid. This behaviour is since the old dvbcut 0.6.x and also with ffmeg 0.7. But the broadcaster were sending correct packets in the past so probably with a change in there broadcasting software the problem started next to another (strange order of packets in the GOP).

5. using higher versions of ffmpeg requires libswresample at least on my system. This may be added to configure.ac.

Overall it was a bit blur which ffmpeg version I should use. Maybe you can name somewhere the version to be used at best.

Thanks and all the best
Cyp

**Comment by bernhardu** [comment]
Sorry for the delay. Thanks for taking care for dvbcut.
Usually I just target the ffmpeg version currently in Debian Testing, currently [this one](https://packages.debian.org/source/bookworm/ffmpeg).
Therefore I did not take care to stay compatible with older versions.

**Comment by bernhardu** [comment]
@cypline: What do you think about 50909b069e ?
CC: @thp

**Comment by cypline** [comment]
@bernhardu: First of all thanks for taking care. The patch you applied is also fine. I tested it and it works as it should.

But I have one remark, as this is also mentioned on the page of QT about pixel manipulation. It is adviced to use the scanline method. Just here as example: setPixel and Pixel are called 3 times per pixel. Each of them will go through preparation of a method call, the methods in the method and this happens 720 times 512. Overall 1.105.920 times.

As I wrote in the pull request I found the reason, why my patch failed. Next to this I created another branch with the alternative of using RGB32 which seems to be the best choice for rendering according to the documentation of the image formats by QT. The patch is 84e9733cd80dabd431d351f99e74fa44ece29e8b.

**Comment by thp** [comment]
RGB32 (with 1 byte unused for alpha) might also be better for performance (at the cost of 1/3 more memory usage), as pixel values are aligned to 4-byte boundaries then.

That part in 50909b069eea44d383d1974061591ac5014a2833 is definitely useful, even for the original version where the 32-bit check just skips the conversion altogether (not sure if I might have caught it then, as I think I haven't tested the difference image feature when doing the initial patch):

```
    } else {
       fprintf(stderr, "%s: wrong format.\n", __FUNCTION__);
    }
```

**Comment by thp** [comment]
> Usually I just target the ffmpeg version currently in Debian Testing, currently [this one](https://packages.debian.org/source/bookworm/ffmpeg).
> Therefore I did not take care to stay compatible with older versions.

Right now `configure.ac` contains this:

```
FFMPEG_LIBS='-lavformat -lavcodec -lavutil'
AC_SUBST(FFMPEG_LIBS)

AC_CHECK_LIB(swscale, main,
  [AC_DEFINE(HAVE_LIB_SWSCALE, 1, [Define this if you have libswscale.])
  FFMPEG_LIBS="$FFMPEG_LIBS -lswscale"])
```

`configure.ac` already uses `pkg-config` for Qt, and the ffmpeg libs in Debian ship with `pkg-config` files.

This could then also be used for versioned dependencies (to make the build fail at configure time for too old ffmpeg versions) as well as potentially handle implicit dependencies (e.g. `libavcodec` has `Requires.private: libswresample >= 4.7.100, libavutil >= 57.28.100` in its pkg-config file).

Untested, but probably something like this could do the trick -- the version numbers might be off a bit (don't forget to add `FFMPEG_CFLAGS` at the right spot as well as `FFMPEG_LIBS`):

```
PKG_CHECK_MODULES([FFMPEG], [libavcodec >= 59.37 libavformat >= 59.27 libavutil >= 57.28 swscale >= 6.7])
AC_SUBST([FFMPEG_CFLAGS])
AC_SUBST([FFMPEG_LIBS])

```

**Comment by bernhardu** [comment]
Hello @cypline, hello @thp, thanks for your input.
I pushed now 182cc2b44 avoiding the pixel/setPixel functions.

**Comment by thp** [comment]
> Hello @cypline, hello @thp, thanks for your input.
> I pushed now [182cc2b](https://github.com/bernhardu/dvbcut-deb/commit/182cc2b448debdc0e1771adcf0571cd49c48fdd6) avoiding the pixel/setPixel functions.

To be on the safe side, use [`im.bytesPerLine()`](https://doc.qt.io/qt-6/qimage.html#bytesPerLine) instead of `im.width()*3`, just in case scanlines are not tightly packed (e.g. when the width isn't a multiple of 4, as QImage seems to [guarantee scanlines are at least 32-bit](https://doc.qt.io/qt-6/qimage.html#scanLine) (and in some cases 64-bit) aligned.

Also, since [`QRgb`](https://doc.qt.io/qt-6/qcolor.html#QRgb-typedef) (despite the name) is actually 32-bit (4 x 8-bit values, including alpha channel), not sure if it's actually correct to access it like this, but it's probably fine if it works for you :)

**Comment by cypline** [comment]
Hello @bernhardu, @thp,

first of all thank you for working so fast on it and for the really good collaboration. I think we can close this issue, as most of the topics are solved and the rest is addressed.

If you are considering to change the configure.ac I would propose not to be too restrictive with the ffmpeg versions, as it will be then less complicated to be made available to other distributions. E.g. I had to downgrade the required version of autoconfig in configure.ac to even start, but there was no real reason to have version 2.71 as requirement.
The minimum requirement of ffmpeg is 3.4 as I tested it and only because of the introduction of the send and receive mechanism adopted as now standard of ffmpeg. Before it was even 2.8. The mentioned issue with the dependency towards libswresample was introduced by ffmpeg 4, so libavcodec >= 58 at least on my system. But also strange that it does not appear on your side and that it it not is reflected in the pkgconfig, only on the Requires.private side. I was compiling all versions of ffmpeg with the same parameters.

Best regards,
Cyp

**Comment by cypline** [comment]
Hello @bernhardu, @thp,

I  discovered another part of the code that was broken by the change of avframe. In dvbcut.cpp line 1337 again there is the check for 32 bit based pictures. And therefore the calc_distance returns always 0.

Best regards,
Cyp

**Comment by bernhardu** [comment]
> To be on the safe side, use [`im.bytesPerLine()`](https://doc.qt.io/qt-6/qimage.html#bytesPerLine) instead of `im.width()*3`, just in case scanlines are not tightly packed

@thp: Thanks for pointing this out, I changed that again.

> I discovered another part of the code that was broken by the change of avframe. In dvbcut.cpp line 1337 again there is the check for 32 bit based pictures. And therefore the calc_distance returns always 0.

@cypline: Thanks for spotting this, I tried to change this and also near line 1166 to work with RGB888.


For the configure change I am undecided, otherwise I hope all aspects of this issue are then handled?

**Comment by cypline** [comment]
Hello @bernhardu,

from my point of view yes. Thank you very much for spending time on it.

Best regards,
Frank
