### ISSUE TITLE
Incorrect frames written by dvbcut/ffmpeg when the cutpoints are not on I-frames

### ISSUE THREAD

**Issue by Vienna550** [bernhardu/dvbcut-deb#3]
Hello
and first of all let me say a big, big thank you for your further development, porting it to Qt5 & maintaining of Dvbcut. Basically for keeping the application still "alive" and fully usable and that's really great. Your efforts are highly appreciated!  

Dvbcut is still one of the very few tools available which manages to cut and edit MPEG2 with absolute, perfect frame-accurancy without reencoding the complete source-material. An enormous advantage, especially when most other programs like Avidemux are limited to  cut only on I-frames. Dvbcut is fast, precise and the cutting is visibly lossless. 

Unfortunately something changed when FFmpeg introduced version 2.0. Since then cuts on B- and P-frames show some weird inconsistencies (when dvbcut/ffmpeg has to do a bit of reencoding). Around the cutpoints the frames are encoded in 50fps till the next I-frame, then they fall back to the correct 25fps, because at this point there is no encoding necessary anymore. If you remove a couple of commercials from TV-recordings it creates a strange mix of a 25fps/50fps video. The issue is described in detail already here:

https://www.mail-archive.com/dvbcut-user@lists.sourceforge.net/msg01252.html

> When:
> * starting an export on a B-frame or P-frame then the reloaded file starts at 
> 50fps and reverts to 25fps after a small number of I-Frames.
> * ending an export on a B-frame or P-frame then the reloaded file can jump from 
> 25fps to 50fps at the end.
> * starting and ending on I-Frame then everything shows 25fps

Usually there are no problems with these files, most software- and hardware-videoplayers will play these videos just fine without any noticeable problems. One exception seems to be the Panasonic DMP-BDT184, which produces some annoying flickering with DVDs created from such videos when the 25/50fps-switching happens. After 1-2 seconds its back to normal again. Mplayer sometimes reports the framerate of such videos not as 25fps, but as 25,233, 25,366 and so on. DVDStyler forces you to encode the complete video when Dvbcut has reencoded some frames on the beginning of the video on B-/P-frames, because it sees them als 50fps-video and therefore is not compliant with the standard DVD-Video.

A solution for this problem is already available here:
https://www.mail-archive.com/dvbcut-user@lists.sourceforge.net/msg01254.html

The patch is already applied to the Dvbcut Version rpmfusion.org provides for Fedora, but it is the old version 0.6.1. Is it possible to apply the timebase-patch also to your 0.7.2 to produce correctly written fps throughout the whole video when there are cuts on non I-frames?

Thanks a lot for your time and efforts!

**Comment by bernhardu** [comment]
Thanks for your investigation.

I had a look at the [src.rpm](http://download1.rpmfusion.org/free/fedora/development/rawhide/Everything/source/SRPMS/d/dvbcut-0.6.1-28.svn179.fc29.src.rpm) from rpmfusion, but I fail somehow to find that patch from [msg01253.html](https://www.mail-archive.com/dvbcut-user@lists.sourceforge.net/msg01253.html) to be contained or referenced inside the src.rpm or in [dvbcut-svn179.tar.bz2](https://pkgs.rpmfusion.org/repo/pkgs/free/dvbcut/dvbcut-svn179.tar.bz2/467975975bc7bf6abcb559449e776654/dvbcut-svn179.tar.bz2).

Therefore my concern if the rpmfusion.org version has really that fix applied, or used some other way?

**Comment by bernhardu** [comment]
Wolfram Gloge's patch still applies and I could also observe it making mplayer not showing the "50.000 fps", when cutting at an B-frame, like before.

So I am going to appy it, but still, I wonder why the rpmfusion.org RPMs do not show it even when not having that patch applied?

**Comment by Vienna550** [comment]
Hello 
and thank you for your reply! it is really great that the timebase-patch from Wolfgang Gloge can be applied to Dvbcut 0.7.2. That's some very good news...

**Referring to Dvbcut 0.6.1.27.svn179 from rpmfusion.org:** Yes, the timebase-patch seems to be missing and looking at the mpgfile.cpp I can't find the relevant codelines there. Therefore I don't think the rpmfusion-packagers have exactly this patch applied. The packaging guidelines are very strict and there's no mention of it in the spec-file or elsewhere. That wouldn't happen and maybe there's indeed another possibility to solve this...

On the other hand - there are several other ffmpeg-patches included (but nothing resembles the timebase-patch imho):

- dvbcut-svn179-ffmpeg-0.11.1.patch
- dvbcut-svn179-ffmpeg-2.0-compatibility.patch
- dvbcut-svn179-ffmpeg-2.4.3-compatibility.patch
- dvbcut-svn179-ffmpeg-3.0.3-compatibility.patch
- ffmpeg35_buildfix.patch

One of the bigger changes seems to be:

> * Sat Nov  5 2016 David Timms <iinet.net.au at dtimms> - 0.6.1-19.svn179
- rebuild for ffmpeg-3.0.3
- add combined patch covering:
- ffmpeg-3.0.3 for removed deprecated definitions and functions.

Looks like it is a real challenge to keep Dvbcut working on recent Linux-distributions and the FFmpeg-developers don't seem to make the job any easier ;-)

Checked Dvbcut from rpmfusion again - just to make 100% sure. The 25/50fps switching on cutpoints when they are not I-frames simply don't appear there. Tested it thoroughly with a 90sec MPEG2 from TV and made cuts every 5 seconds on B/P frames. Result: Clean, continues & constant 25fps throughout the whole video, exactly how it should be.  

I'm afraid I'm pretty much of zero usable help here, but imho if the timebase-patch stops the weird doubling of the framerate around the cutpoints (when reencoding is necessary), then I'd say "Problem solved" and Dvbcut will be one of finest applications to cut and edit videos as long as MPEG2 will be around. 

Thanks a lot for your quick help and for solving this issue so quickly! You are my hero of the day!

Best regards and enjoy the rest of the weekend!
